### ISSUE TITLE
Thumb key is off-centered in MX files

### ISSUE THREAD

**Issue by sporkus** [weteor/Kong#1]
Hi Weteor,

Thanks for your wonderful designs. I am getting the Kong and Spc Evdr fabricated right now.

It looks like a 3u switch footprint for the Kong MX is off centered for all 1u or 3u configuration (the first 3u footprint left from center). I can see it in the MX and combined production gerber files, and the kicad files as well. It doesn't affect the 2u build like yours.

Current state/production gerbers:
<img width="771" alt="image" src="https://user-images.githubusercontent.com/102923689/226964342-a39e4476-c308-4379-bd3f-d0f74d229428.png">

Fixed:
<img width="763" alt="image" src="https://user-images.githubusercontent.com/102923689/226963982-d1276153-22ef-45c4-9d3f-23d4974b4bc4.png">

I can make a PR for the fix if you'd like me to.

Thanks!

**Comment by weteor** [comment]
Hi, 

thanks a lot for noticing and letting me know, totally missed that.

I've fixed the issue and uploaded new files!

Hope you will enjoy those boards!

**Comment by sporkus** [comment]
Hey one more thing, in the BOM, LSCS part number for the usb-c connector is for USB-C-31-M-12 (surface mount), but the footprint is USB-C-31-M-14(mid mount). 

I know in the docs you suggested hand soldering the mid-mount version, so It might be better to remove the connector from the BOM. I went the other way, swapping the footprint back to M-12 for PCBA.

**Comment by weteor** [comment]
Right. The footprint value in the BOM was incorrect, position file and LSCS number are correct.

Fixed that, shouldn't have been a problem though.

Just to be clear:
MX version uses surface mount  USB-C-31-M-12, which can be assembled without extra cost
Choc version uses mid mount USB-C-31-M-14, which I've taken out of the BOM, so it can be hand soldered.

Thanks again for pointing that out.
